### ISSUE TITLE
Roadmap for Train-Pwsh Completion

### ISSUE THREAD

**Issue by skandwal-mitre** [mitre/train-pwsh#1]
- [X] Split custom resource into 2-4 individual resources for compatible Powershell modules.
- [x] Make sure the correct function names are being used based on parent class. Functionality should be copied from the custom resource already made.  
- [x] Ensure options for train are working correctly and pulling data from the right place.
- [x] Edit custom resource to only have stdout, sterr, exit_status and get the session from train.
- [x] Edit controls to call custom resource and get/check data. 
- [x] Make sure train is run correctly using correct syntax
